package de.syscy.kagecloud.webserver.pages.webcomponents.util;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import lombok.experimental.UtilityClass;

public interface SCIcon {
	public static final SCIcon NONE = Default.NONE;

	public String name();

	default public String getFAClassName() {
		return "fa-" + name().toLowerCase().replaceAll("_", "-");
	}

	@UtilityClass
	public static class Util {
		private List<SCIcon> allIcons = new ArrayList<>();

		static {
			allIcons.addAll(Arrays.asList(Web.values()));
			allIcons.addAll(Arrays.asList(Accessibility.values()));
			allIcons.addAll(Arrays.asList(Hand.values()));
			allIcons.addAll(Arrays.asList(Transportation.values()));
			allIcons.addAll(Arrays.asList(Gender.values()));
			allIcons.addAll(Arrays.asList(File.values()));
			allIcons.addAll(Arrays.asList(Spinner.values()));
			allIcons.addAll(Arrays.asList(Form.values()));
			allIcons.addAll(Arrays.asList(Payment.values()));
			allIcons.addAll(Arrays.asList(Chart.values()));
			allIcons.addAll(Arrays.asList(Currency.values()));
			allIcons.addAll(Arrays.asList(TextEditor.values()));
			allIcons.addAll(Arrays.asList(Directional.values()));
			allIcons.addAll(Arrays.asList(VideoPlayer.values()));
			allIcons.addAll(Arrays.asList(Brand.values()));
			allIcons.addAll(Arrays.asList(Medical.values()));
		}

		public SCIcon getByName(String name) {
			name = name.replace(' ', '_');

			for(SCIcon icon : allIcons) {
				if(icon.name().equalsIgnoreCase(name)) {
					return icon;
				}
			}

			return Default.NONE;
		}
	}

	public static enum Default implements SCIcon {
		NONE;

		@Override
		public String getFAClassName() {
			return "";
		}

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Web implements SCIcon {
		//@formatter:off
		ADJUST, AMERICAN_SIGN_LANGUAGE_INTERPRETER, ANCHOR, ARCHIVE, AREA_CHART, ARROWS, ARROW_H, ARROWS_V,
		ASL_INTERPRETING, ASSISTIVE_LISTENING_SYSTEM, ASTERISK, AT, AUDIO_DESCRIPTION, AUTOMOBILE,
		BALANCE_SCALE, BAN, BANK, BAR_CHART, BAR_CHART_O, BARCODE, BARS, BATTERY_0, BATTERY_1, BATTERY_2,
		BATTERY_3, BATTERY_4, BATTERY_EMPTY, BATTERY_FULL, BATTERY_HALF, BATTERY_QUARTER,
		BATTERY_THREE_QUARTERS, BED, BEER, BELL, BELL_O, BELL_SLASH, BELL_SLASH_O, BICYCLE, BINOCULARS,
		BIRTHDAY_CAKE, BLIND, BLUETOOTH, BLUETOOTH_B, BOLT, BOMB, BOOK, BOOKMARK, BOOKMARK_O, BRAILLE,
		BRIEFCASE, BUG, BUILDING, BUILDING_O, BULLHORN, BULLSEYE, BUS, CAB, CALCULATOR, CALENDAR,
		CALENDAR_CHECK_O, CALENDAR_MINUS_O, CALENDAR_O, CALENDAR_PLUS_O, CALENDAR_TIMES_O, CAMERA,
		CAMERA_RETRO, CAR, CARET_SQUARE_O_DOWN, CARET_SQUARE_O_LEFT, CARET_SQUARE_O_RIGHT,
		CARET_SQUARE_O_UP, CART_ARROW_DOWN, CART_PLUS, CC, CERTIFICATE, CHECK, CHECK_CIRCLE, CHECK_CIRCLE_O,
		CHECK_SQUARE, CHECK_SQUARE_O, CHILD, CIRCLE, CIRCLE_O, CIRCLE_O_NOTCH, CIRCLE_THIN, CLOCK_O,
		CLONE, CLOSE, CLOUD, CLOUD_DOWNLOAD, CLOUD_UPLOAD, CODE, CODE_FORK, COFFEE, COG, COGS, COMMENT,
		COMMENT_O, COMMENTING, COMMENTING_O, COMMENTS, COMMENTS_O, COMPASS, COPYRIGHT,
		CREATIVE_COMMONS, CREDIT_CARD, CREDIT_CARD_ALT, CROP, CROSSHAIRS, CUBE, CUBES, CUTLERS,
		DASHBOARD, DATABASE, DEAF, DEAFNESS, DESKTOP, DIAMOND, DOT_CIRCLE_O, DOWNLOAD, EDIT, ELLIPSIS_H,
		ELLIPSIS_V, ENVELOPE, ENVELOPE_O, ENVELOPE_SQUARE, ERASER, EXCHANGE, EXCLAMATION, EXCLAMATION_CIRCLE,
		EXCLAMATION_TRIANGLE, EXTERNAL_LINK, EXTERNAL_LINK_SQUARE, EYE, EYE_SLASH, EYEDROPPER, FAX, FEED,
		FEMALE, FIGHTER_JET, FILE_ARCHIVE_O, FILE_AUDIO_O, FILE_CODE_O, FILE_EXCEL_O, FILE_IMAGE_O,
		FILE_MOVIE_O, FILE_PDF_O, FILE_PHOTO_O, FILE_PICTURE_O, FILE_POWERPOINT_O, FILE_SOUND_O, FILE_VIDEO_O,
		FILE_WORD_O, FILE_ZIP_O, FILM, FILTER, FIRE, FIRE_EXTINGUISHER, FLAG, FLAG_CHECKERED, FLAG_O,
		FLASH, FLASK, FOLDER, FOLDER_O, FOLDER_OPEN, FOLDER_OPEN_O, FROWN_O, FUTBOL_O, GAMEPAD, GAVEL, GEAR,
		GEARS, GIFT, GLASS, GLOBE, GRADUATION_CAP, GROUP, HAND_GRAB_O, HAND_LIZARD_O, HAND_PAPER_O,
		HAND_PEACE_O, HAND_POINTER_O, HAND_ROCK_O, HAND_SCISSORS_O, HAND_SPOCK, HAND_STOP_O, HARD_OF_HEARING,
		HASHTAG, HDD_O, HEADPHONES, HEART, HEART_O, HEARTBEAT, HISTORY, HOME, HOTEL, HOURGLASS, HOURGLASS_1,
		HOURGLASS_2, HOURGLASS_3, HOURGLASS_END, HOURGLASS_HALF, HOURGLASS_O, HOURGLASS_START, I_CURSOR,
		IMAGE, INBOX, INDUSTRY, INFO, INFO_CIRCLE, INSTITUTION, KEY, KEYBOARD_O, LANGUAGE, LAPTOP, LEAF,
		LEGAL, LEMON_O, LEVEL_DOWN, LEVEL_UP, LIFE_BOUY, LIFE_RING, LIFE_SAVER, LIGHTBULB_O, LINE_CHART,
		LOCATION_ARROW, LOCK, LOW_VISION, MAGIC, MAGNET, MAIL_FORWARD, MAIL_REPLY, MAIL_REPLY_ALL, MALE,
		MAP, MAP_MARKER, MAP_O, MAP_PIN, MAP_SIGNS, MEH_O, MICROPHONE, MICROPHONE_SLASH, MINUS, MINUS_CIRCLE,
		MINUS_SQUARE, MINUS_SQUARE_O, MOBILE, MOBILE_PHONE, MONEY, MOON_O, MORTAR_BOARD, MOTORCYCLE,
		MOUSE_POINTER, MUSIC, NAVICON, NEWSPAPER_O, OBJECT_GROUP, OBJECT_UNGROUP, PAINT_BRUSH, PAPER_PLANE,
		PAPER_PLANE_O, PAW, PENCIL, PENCIL_SQUARE, PENCIL_SQUARE_O, PERCENT, PHONE, PHONE_SQUARE, PHOTO,
		PICTURE_O, PIE_CHART, PLANE, PLUG, PLUS, PLUS_CIRCLE, PLUS_SQUARE, PLUS_SQUARE_O, POWER_OFF,
		PRINT, PUZZLE_PIECE, QRCODE, QUESTION, QUESTION_CIRCLE, QUESTION_CIRCLE_O, QUOTE_LEFT, QUOTE_RIGHT,
		RANDOM, RECYCLE, REFRESH, REGISTERED, REMOVE, REORDER, REPLY, REPLY_ALL, RETWEET, ROAD, ROCKET,
		RSS, RSS_SQUARE, SEARCH, SEARCH_MINUS, SEARCH_PLUS, SEND, SEND_O, SERVER, SHARE, SHARE_ALT,
		SHARE_ALT_SQUARE, SHARE_SQUARE, SHARE_SQUARE_O, SHIELD, SHIP, SHOPPING_BAG, SHOPPING_BASKET,
		SHOPPING_CART, SIGN_IN, SIGN_LANGUAGE, SIGN_OUT, SIGNAL, SIGNING, SITEMAP, SLIDERS, SMILE_O,
		SOCCER_BALL_O, SORT, SORT_ALPHA_ASC, SORT_ALPHA_DESC, SORT_AMOUNT_ASC, SORT_AMOUNT_DESC,
		SORT_ASC, SORT_DESC, SORT_DOWN, SORT_NUMERIC_ASC, SORT_NUMERIC_DESC, SORT_UP, SPACE_SHUTTLE,
		SPINNER, SPOON, SQUARE, SQUARE_O, STAR, STAR_HALF, STAR_HALF_EMPTY, STAR_HALF_FULL, STAR_HALF_O,
		STAR_O, STICKY_NOTE, STICKY_NOTE_O, STREET_VIEW, SUITCASE, SUN_O, SUPPORT, TABLET, TACHOMETER, TAG,
		TAGS, TASKS, TAXI, TELEVISION, TERMINAL, THUMB_TACK, THUMBS_DOWN, THUMBS_O_DOWN, THUMBS_O_UP,
		THUMBS_UP, TICKET, TIMES, TIMES_CIRCLE, TIMES_CIRCLE_O, TINT, TOGGLE_DOWN, TOGGLE_LEFT, TOGGLE_OFF,
		TOGGLE_ON, TOGGLE_RIGHT, TOGGLE_UP, TRADEMARK, TRASH, TRASH_O, TREE, TROPHY, TRUCK, TTY, TV,
		UMBRELLA, UNIVERSAL_ACCESS, UNIVERSITY, UNLOCK, UNLOCK_ALT, UNSORTED, UPLOAD, USER, USER_PLUS,
		USER_SECRET, USER_TIMES, USERS, VIDEO_CAMERA, VOLUME_CONTROL_PHONE, VOLUME_DOWN, VOLUME_OFF,
		VOLUME_UP, WARNING, WHEELCHAIR, WHEELCHAIR_ALT, WIFI, WRENCH;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Accessibility implements SCIcon {
		//@formatter:off
		AMERICAN_SIGN_LANGUAGE_INTER_PRETER, ASL_INTERPRETING, ASSISTIVE_LISTENING_SYSTEMS, AUDIO_DESCRIPTION,
		BLIND, BRAILLE, CC, DEAF, DEAFNESS, HARD_OF_HEARING, LOW_VISION, QUESTION_CIRCLE_O, SIGN_LANGUAGE,
		SIGNING, TTY, UNIVERSAL_ACCESS, VOLUME_CONTROL_PHONE, WHEELCHAIR, WHEELCHAIR_ALT;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Hand implements SCIcon {
		//@formatter:off
		HAND_GRAB_O, HAND_LIZARD_O, HAND_PAPER_O, HAND_PEACE_O, HAND_POINTER_O, HAND_ROCK_O, HAND_SCISSORS_O,
		HAND_SPOCK, HAND_STOP_O, THUMBS_DOWN, THUMBS_O_DOWN, THUMBS_O_UP, THUMBS_UP;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Transportation implements SCIcon {
		//@formatter:off
		AMBULANCE, AUTOMOBILE, BICYCLE, BUS, CAB, CAR, FIGHTER_JET, MOTORCYCLE, PLANE, ROCKET, SHIP,
		SPACE_SHUTTLE, SUBWAY, TAXI, TRAIN, TRUCK, WHEELCHAIR;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Gender implements SCIcon {
		//@formatter:off
		GENDERLESS, INTERSEX, MARS, MARS_DOUBLE, MARS_STROKE, MARS_STROKE_H, MARS_STROKE_V, MERCURY,
		NEUTER, TRANSGENDER, TRANSGENDER_ALT, VENUS, VENUS_DOUBLE, VENUS_MARS;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum File implements SCIcon {
		//@formatter:off
		FILE, FILE_ARCHIVE_O, FILE_AUDIO_O, FILE_CODE_O, FILE_EXCEL_O, FILE_IMAGE_O, FILE_MOVIE_O,
		FILE_O, FILE_PDF_O, FILE_PHOTO_O, FILE_PICTURE_O, FILE_POWERPOINT_O, FILE_SOUND_O, FILE_TEXT,
		FILE_TEXT_O, FILE_VIDEO_O, FILE_WORD_O, FILE_ZIP_O;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Spinner implements SCIcon {
		//@formatter:off
		CIRCLE_O_NOTCH, COG, GEAR, REFRESH, SPINNER;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Form implements SCIcon {
		//@formatter:off
		CHECK_SQUARE, CHECK_SQUARE_O, CIRCLE, CIRCLE_O, DOT_CIRCLE_O, MINUS_SQUARE, MINUS_SQUARE_O,
		PLUS_SQUARE, PLUS_SQUARE_O, SQUARE, SQUARE_O;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Payment implements SCIcon {
		//@formatter:off
		CC_AMEX, CC_DINERS_CLUB, CC_DISCOVER, CC_JCB, CC_MASTERCARD, CC_PAYPAL, CC_STRIPE, CC_VISA,
		CREDIT_CARD, CREDIT_CARD_ALT, GOOGLE_WALLET, PAYPAL;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Chart implements SCIcon {
		//@formatter:off
		AREA_CHART, BAR_CHART, BAR_CHART_O, LINE_CHART, PIE_CHART;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Currency implements SCIcon {
		//@formatter:off
		BITCOIN, BTC, CNY, DOLLAR, EUR, EURO, GBP, GG, GG_CIRCLE, ILS, INR, JPY, KRW, MONEY, RMB, ROUBLE, RUB,
		RUBLE, RUPEE, SHEKEL, SHEQEL, TRY, TURKISH_LIRA, USD, WON, YEN;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum TextEditor implements SCIcon {
		//@formatter:off
		ALIGN_CENTER, ALIGN_JUSTIFY, ALIGN_LEFT, ALIGN_RIGHT, BOLD, CHAIN, CHAIN_BROKEN, CLIPBOARD, COLUMNS,
		COPY, CUT, DEDENT, ERASER, FILE, FILE_O, FILE_TEXT, FILE_TEXT_O, FILES_O, FLOPPY_O, FONT, HEADER,
		INDENT, ITALIC, LINK, LIST, LIST_ALT, LIST_OL, LIST_UL, OUTDENT, PAPERCLIP, PARAGRAPH, PASTE, REPEAT,
		ROTATE_LEFT, ROTATE_RIGHT, SAVE, SCISSORS, STRIKETHROUGH, SUBSCRIPT, SUPERSCRIPT, TABLE, TEXT_HEIGHT,
		TEXT_WIDTH, TH, TH_LARGE, TH_LIST, UNDERLINE, UNDO, UNLINK;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Directional implements SCIcon {
		//@formatter:off
		ANGLE_DOUBLE_DOWN, ANGLE_DOUBLE_LEFT, ANGLE_DOUBLE_RIGHT, ANGLE_DOUBLE_UP, ANGLE_DOWN, ANGLE_LEFT,
		ANGLE_RIGHT, ANGLE_UP, ARROW_CIRCLE_DOWN, ARROW_CIRCLE_LEFT, ARROW_CIRCLE_O_DOWN, ARROW_CIRCLE_O_LEFT,
		ARROW_CIRCLE_O_RIGHT, ARROW_CIRCLE_O_UP, ARROW_CIRCLE_RIGHT, ARROW_CIRCLE_UP, ARROW_DOWN, ARROW_LEFT,
		ARROW_RIGHT, ARROW_UP, ARROWS, ARROWS_ALT, ARROWS_H, ARROWS_V, CARET_DOWN, CARET_LEFT, CARET_RIGHT,
		CARET_SQUARE_O_DOWN, CARET_SQUARE_O_LEFT, CARET_SQUARE_O_RIGHT, CARET_SQUARE_O_UP, CARET_UP,
		CHEVRON_CIRCLE_DOWN, CHEVRON_CIRCLE_LEFT, CHEVRON_CIRCLE_RIGHT, CHEVRON_CIRCLE_UP, CHEVRON_DOWN,
		CHEVRON_LEFT, CHEVRON_RIGHT, CHEVRON_UP, EXCHANGE, HAND_O_DOWN, HAND_O_LEFT, HAND_O_RIGHT, HAND_O_UP,
		LONG_ARROW_DOWN, LONG_ARROW_LEFT, LONG_ARROW_RIGHT, LONG_ARROW_UP, TOGGLE_DOWN, TOGGLE_LEFT,
		TOGGLE_RIGHT, TOGGLE_UP;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum VideoPlayer implements SCIcon {
		//@formatter:off
		ARROWS_ALT, BACKWARD, COMPRESS, EJECT, EXPAND, FAST_BACKWARD, FAST_FORWARD, FORWARD, PAUSE,
		PAUSE_CIRCLE, PAUSE_CIRCLE_O, PLAY, PLAY_CIRCLE, PLAY_CIRCLE_O, RANDOM, STEP_BACKWARD, STEP_FORWARD,
		STOP, STOP_CIRCLE, STOP_CIRCLE_O, YOUTUBE_PLAY;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Brand implements SCIcon {
		//@formatter:off
		ADN, AMAZON, ANDROID, ANGELLIST, APPLE, BEHANCE, BEHANCE_SQUARE, BITBUCKET, BITBUCKET_SQUARE, BITCOIN,
		BLACK_TIE, BLUETOOTH, BLUETOOTH_B, BTC, BUYSELLADS, CC_AMEX, CC_DINERS_CLUB, CC_DISCOVER, CC_JCB,
		CC_MASTERCARD, CC_PAYPAL, CC_STRIPE, CC_VISA, CHROME, CODEPEN, CODIEPIE, CONNECTDEVELOP, CONTAO,
		CSS3, DASHCUBE, DELICIOUS, DEVIANART, DIGG, DRIBBBLE, DROPBOX, DRUPAL, EDGE, EMPIRE, ENVIRA,
		EXPEDITEDSSL, FA, FACEBOOK, FACEBOOK_F, FACEBOOK_OFFICIAL, FACEBOOK_OFFICIAL_SQUARE, FIREFOX,
		FIRST_ORDER, FLICKR, FONT_AWESOME, FONTICONS, FORT_AWESOME, FORUMBEE, FOURSQUARE, GE, GET_POCKET,
		GG, GG_CIRCLE, GIT, GIT_SQUARE, GITHUB, GITHUB_ALT, GITHUB_SQUARE, GITLAB, GITTIP, GLIDE, GLIDE_G,
		GOOGLE, GOOGLE_PLUS, GOOGLE_PLUS_CIRCLE, GOOGLE_PLUS_OFFICIAL, GOOGLE_PLUS_SQUARE, GOOGLE_WALLET,
		GRATIPAY, HACKER_NEWS, HOUZZ, HTML5, INSTAGRAM, INTERNET_EXPLORER, IOXHOST, JOOMLA, JSFIDDLE, LASTFM,
		LASTFM_SQUARE, LEANPUB, LINKEDIN, LINKEDIN_SQUARE, LINUX, MAXCDN, MEANPATH, MEDIUM, MIXCLOUD, MODX,
		ODNOKLASSNIKI, ODNOKLASSNIKI_SQUARE, OPENCART, OPENID, OPERA, OPTIN_MONSTER, PAGELINES, PAYPAL,
		PIED_PIPER, PIED_PIPER_ALT, PIED_PIPER_PP, PINTEREST, PINTEREST_P, PINTEREST_SQUARE, PRODUCT_HUNT,
		QQ, RA, REBEL, REDDIT, REDDIT_ALIEN, REDDIT_SQUARE, RENREN, RESISTANCE, SAFARI, SCRIBD, SELLSY,
		SHARE_ALT, SHARE_ALT_SQUARE, SHIRTSINBULK, SIMPLYBUILT, SKYATLAS, SKYPE, SLACK, SLIDESHARE, SNAPCHAT,
		SNAPCHAT_GHOST, SNAPCHAT_SQUARE, SOUNDCLOUD, SPOTIFY, STACK_EXCHANGE, STACK_OVERFLOW, STEAM,
		STEAM_SQUARE, STUMBlEUPON, STUMBLEUPON_CIRCLE, TENCENT_WEIBO, THEMEISLE, TRELLO, TRIPADVISOR, TUMBLR,
		TUMBLR_SQUARE, TWITCH, TWITTER, TWITTER_SQUARE, USB, VIACOIN, VIADEO, VIADEO_SQUARE, VIMEO,
		VIMEO_SQUARE, VINE, VK, WECHAT, WEIBO, WEIXIN, WHATSAPP, WIKIPEDIA_W, WINDOWS, WORDPRESS, WPBEGINNER,
		WPFORMS, XING, XING_SQUARE, Y_COMBINATOR, Y_COMBINATOR_SQUARE, YAHOO, YC, YC_SQUARE, YELP, YOAST,
		YOUTUBE, YOUTUBE_PLAY, YOUTUBE_SQUARE;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}

	public static enum Medical implements SCIcon {
		//@formatter:off
		AMBULANCE, H_SQUARE, HEART, HEART_O, HEARTBEAT, HOSPITAL_O, MEDKIT, PLUS_SQUARE, STETHOSCOPE,
		USER_MD, WHEELCHAIR;
		//@formatter:on

		@Override
		public String toString() {
			return getFAClassName();
		}
	}
}